### ISSUE TITLE
Many drop rates are considered invalid

### ISSUE THREAD

**Issue by fuzxi** [Jallah123/Dry-Calculator#1]
![2022-08-17-01-15-41](https://user-images.githubusercontent.com/33790641/185069533-1ffafb2d-205e-4d05-a309-6c380b3699e6.png)
![2022-08-17-01-15-18](https://user-images.githubusercontent.com/33790641/185069538-dd680545-a4a1-494c-a3d8-5d40070c8d4f.png)
![2022-08-17-01-15-12](https://user-images.githubusercontent.com/33790641/185069540-77b495dd-4fed-47ba-af30-0e800c7e92d8.png)
![2022-08-17-01-14-35](https://user-images.githubusercontent.com/33790641/185069544-d75ac842-76ae-4219-9c77-226a6c7ddefd.png)

**Comment by Jallah123** [comment]
fixed in next version
