### ISSUE TITLE
Incorrect dryness messaging

### ISSUE THREAD

**Issue by fuzxi** [Jallah123/Dry-Calculator#2]
Getting heavily spooned shows a skeleton, which I assume is intended for going very dry.
![2022-08-17-01-22-39](https://user-images.githubusercontent.com/33790641/185071005-ce9d7137-d204-4054-9fca-db9b048e6c3a.png)
Getting no drops while well below drop rate shows Oprah, which I assume is intended for getting heavily spooned ("and you get a drop, and you get a drop, everybody gets a drop!").
![2022-08-17-01-26-27](https://user-images.githubusercontent.com/33790641/185071845-e3b96f43-bf24-4109-8d11-a0dbabe94efe.png)

**Comment by Jallah123** [comment]
fixed in next version
