### ISSUE TITLE
Setting KC too high locks up RuneLite for duration of calculation

### ISSUE THREAD

**Issue by fuzxi** [Jallah123/Dry-Calculator#3]
Setting drop rate to 1/1000, KC to 3,000,000 and drops to 0 prevents any interaction with the client for approximately 5 seconds. Setting KC to 10,000,000 locks up the client for 30 seconds. This is on an AMD R5 5600.

If deprioritizing the calculation so it doesn't take precedence over the rest of the client functions is possible, that would be ideal. Otherwise, maybe you could put a cap on the KC input, or stop the calculation after reaching however many digits of precision.

**Comment by Jallah123** [comment]
fixed in next version
